source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
target 'Order' do
end
pod 'HMSegmentedControl'
pod 'IQKeyboardManager'
pod 'PureLayout'
pod 'UITableView+FDTemplateLayoutCell'
pod 'WXTabBarController', '~> 0.1'
